### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by robzai** [seanmcneil/Spitfire#1]
got EXC_BAD_ACCESS error. I was trying to convert images from photo library to movie. It works fine when I choose one or two photos, but it crash if I choose four or more images. Error shows up at line "context.draw(cgImage, in: rect)" in PixelBuffer.siwf

**Comment by seanmcneil** [comment]
Any chance you can provide me the images you were using?

**Comment by robzai** [comment]
https://github.com/robzai/photoToMovie
Here's the link to my project. And I attach a zip file of the images and a screenshot of the error. Btw, I was testing in simulator. It crash randomly, some times evernthing works fine and some time it crash.
[untitled folder.zip](https://github.com/seanmcneil/Spitfire/files/1079709/untitled.folder.zip)
<img width="1235" alt="wx20170615-204044 2x" src="https://user-images.githubusercontent.com/15989948/27211252-e4b4e674-520c-11e7-8371-f792a903c819.png">

**Comment by seanmcneil** [comment]
Thanks, will try and look into it this weekend and let you know what I find.

**Comment by seanmcneil** [comment]
I looked into it this morning, and found that there were at least two images that were crashing that spot. I wound up rewriting a new resize function that did solve the problem for me, since they were coming through with incorrect dimensions:

```
extension UIImage {
    func resize() -> UIImage? {
        let size = CGSize(width: 1920.0, height: 1080.0)
        UIGraphicsBeginImageContext(size)
        draw(in: CGRect(origin: .zero, size: size))
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return image
    }
}
```

As to why it is crashing with those values in the app, I will have to update it to implement a new guard statement to check for it.

**Comment by robzai** [comment]
Thanks for the update. I found something on stackoverflow.
https://stackoverflow.com/questions/40788480/how-do-i-export-uiimage-array-as-a-movie-in-swift-3
The code in this post seems working fine.
