### ISSUE TITLE
The operation couldn’t be completed. (Spitfire.SpitfireError error 1.)

### ISSUE THREAD

**Issue by MehdiChennoufi** [seanmcneil/Spitfire#2]
Hi there, 

Firstly, thanks you for this code, it save me a lot of time !

Secondly, I'd like to know what are (and where I can find) the informations/settings on image size ?

I tested with many images format and I notice hat I got this error very often but its not very explicit, I did get it when I change my image size but what is the limit of Height/Width to avoid any issue ?

I tried you extension in a previous Issue, it works but I'm not sure this is the best answer for a long term solution.

Can you bring me some light here ?

Later, I will mix my video (a image in portrait) with other videos in a mixComposition, but first I need to be sure about the image format to use with my others videos, recorded in portrait too (front camera)

**Edit:** I removed the localizedDescription for the error int the catch block of spitfire.makeVideo() and got a much understandable answer : 

>ImageDimensionsMultiplierFailure("Image width must be divisble by 16")

Thanks

**Comment by seanmcneil** [comment]
Hi,

Sorry for the delay, as I rarely check this account now :(

Thanks for the comment, appreciate it! 

Sorry about the confusion regarding the image size, as you pointed out, it is a bit opaque to access. While I would like to perform a full re-write on this to modernize the code and improve visibility into errors, I simply have not had much time for doing that as I do not actively use this in any of my projects. 

Regarding your specific error though, that is an issue I believe brought up by AVFoundation as it cannot properly encode a video with image sizes that do not adhere to the "divisible by 16" rule, so I enforce it via the guard statement you encounter.

Regards
